// ============================================================
// MOCK DATA — Base de datos simulada con datos realistas
// ============================================================

// Refugios reales (inspirados en fundaciones latinoamericanas)
export const SHELTERS = [
  {
    id: 'shelter-1',
    name: 'Fundación Paz Animal',
    location: { latitude: 3.4516, longitude: -76.5320 },
    address: 'Barrio San Fernando, Cali',
    phone: '+57 304 555 1234',
    description: 'Refugio dedicado al rescate y rehabilitación de perros callejeros desde 2015.',
    dogsCount: 34,
    volunteersNeeded: 12,
    rating: 4.8,
  },
  {
    id: 'shelter-2',
    name: 'Peluditos del Valle',
    location: { latitude: 3.3951, longitude: -76.5330 },
    address: 'Ciudad Jardín, Cali',
    phone: '+57 312 555 5678',
    description: 'Organización sin ánimo de lucro enfocada en la adopción responsable.',
    dogsCount: 22,
    volunteersNeeded: 8,
    rating: 4.6,
  },
  {
    id: 'shelter-3',
    name: 'Refugio Corazón Canino',
    location: { latitude: 3.4721, longitude: -76.5278 },
    address: 'Barrio Granada, Cali',
    phone: '+57 318 555 9012',
    description: 'Finca-refugio con amplio espacio para perros rescatados.',
    dogsCount: 48,
    volunteersNeeded: 20,
    rating: 4.9,
  },
];

// Dueños reales de mascotas
export const OWNERS = [
  {
    id: 'owner-1',
    name: 'Carlos Ruiz',
    location: { latitude: 3.4350, longitude: -76.5400 },
    address: 'Barrio El Peñón, Cali',
    phone: '+57 300 123 4567',
    description: 'Dueño de Bruno. Trabajo todo el día y necesito ayuda con su paseo al mediodía.',
    rating: 4.9,
  },
  {
    id: 'owner-2',
    name: 'Ana Gómez',
    location: { latitude: 3.3850, longitude: -76.5300 },
    address: 'Barrio Ciudad Jardín, Cali',
    phone: '+57 310 987 6543',
    description: 'Buscando alguien de confianza para pasear a Thor los fines de semana.',
    rating: 5.0,
  },
  {
    id: 'owner-3',
    name: 'Mónica Velez',
    location: { latitude: 3.4516, longitude: -76.5320 },
    address: 'Barrio San Fernando, Cali',
    phone: '+57 315 123 9876',
    description: 'Necesito apoyo con los paseos de mis perritos entre semana.',
    rating: 4.8,
  },
  {
    id: 'owner-4',
    name: 'Daniel Vargas',
    location: { latitude: 3.4721, longitude: -76.5278 },
    address: 'Barrio Granada, Cali',
    phone: '+57 320 555 4433',
    description: 'Mi perro es mayor y necesita paseos lentos y tranquilos.',
    rating: 4.7,
  },
];


// Perros con datos realistas y completos
export const DOGS = [
  {
    id: 'dog-1',
    name: 'Luna',
    breed: 'Criolla (mestiza)',
    age: 3,
    weight: 18,
    gender: 'Hembra',
    photo: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=400&q=50',
    ownerId: 'owner-3',
    energyLevel: 'alto', // alto, medio, bajo
    temperament: ['amigable', 'juguetona', 'sociable'],
    specialNeeds: [],
    healthStatus: 'saludable',
    vaccinationStatus: 'al día',
    sppiayed: true,
    description: 'Luna es una perrita rescatada de la calle. Es muy cariñosa y le encanta jugar con otros perros.',
    daysSinceLastWalk: 3,
    totalWalks: 12,
    preferredWalkTime: 'mañana',
    anxietyLevel: 'bajo', // bajo, medio, alto
    size: 'mediano', // pequeño, mediano, grande
    walkDurationPreferred: 45, // minutos
    goodWithKids: true,
    goodWithOtherDogs: true,
    adoptionReady: true,
    dateRescued: '2024-08-15',
    interactionHistory: [
      { date: '2026-04-25', volunteerId: 'vol-1', type: 'paseo', duration: 40, rating: 5, notes: 'Muy contenta, jugó mucho.' },
      { date: '2026-04-20', volunteerId: 'vol-2', type: 'paseo', duration: 30, rating: 4, notes: 'Tiró un poco de la correa al principio.' },
    ],
  },
  {
    id: 'dog-2',
    name: 'Rocky',
    breed: 'Pitbull mix',
    age: 5,
    weight: 28,
    gender: 'Macho',
    photo: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=400&q=50',
    ownerId: 'owner-3',
    energyLevel: 'alto',
    temperament: ['leal', 'protector', 'energético'],
    specialNeeds: ['necesita paseador con experiencia'],
    healthStatus: 'saludable',
    vaccinationStatus: 'al día',
    sppiayed: true,
    description: 'Rocky fue rescatado de un caso de maltrato. Con paciencia y cariño, se ha convertido en un perro muy leal.',
    daysSinceLastWalk: 5,
    totalWalks: 8,
    preferredWalkTime: 'tarde',
    anxietyLevel: 'medio',
    size: 'grande',
    walkDurationPreferred: 60,
    goodWithKids: false,
    goodWithOtherDogs: false,
    adoptionReady: false,
    dateRescued: '2024-03-20',
    interactionHistory: [
      { date: '2026-04-22', volunteerId: 'vol-1', type: 'paseo', duration: 50, rating: 4, notes: 'Necesita más socialización.' },
    ],
  },
  {
    id: 'dog-3',
    name: 'Canela',
    breed: 'Labrador mix',
    age: 2,
    weight: 22,
    gender: 'Hembra',
    photo: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?auto=format&fit=crop&w=400&q=50',
    ownerId: 'owner-1',
    energyLevel: 'medio',
    temperament: ['tranquila', 'obediente', 'cariñosa'],
    specialNeeds: [],
    currentRequest: {
      date: 'Hoy, 2 de mayo',
      time: '3:00 PM - 3:20 PM',
      duration: 20,
      route: 'Parque del Perro → Av. San Fernando'
    },
    healthStatus: 'saludable',
    vaccinationStatus: 'al día',
    sppiayed: true,
    description: 'Canela llegó al refugio siendo cachorra. Es muy obediente y perfecta para familias.',
    daysSinceLastWalk: 1,
    totalWalks: 25,
    preferredWalkTime: 'mañana',
    anxietyLevel: 'bajo',
    size: 'mediano',
    walkDurationPreferred: 30,
    goodWithKids: true,
    goodWithOtherDogs: true,
    adoptionReady: true,
    dateRescued: '2024-11-10',
    interactionHistory: [
      { date: '2026-04-28', volunteerId: 'vol-3', type: 'paseo', duration: 35, rating: 5, notes: 'Excelente compañera.' },
      { date: '2026-04-26', volunteerId: 'vol-1', type: 'visita', duration: 20, rating: 5, notes: 'Muy tranquila.' },
      { date: '2026-04-23', volunteerId: 'vol-2', type: 'paseo', duration: 40, rating: 5, notes: 'Caminó perfecto con correa.' },
    ],
  },
  {
    id: 'dog-4',
    name: 'Thor',
    breed: 'Pastor Alemán mix',
    age: 4,
    weight: 32,
    gender: 'Macho',
    photo: 'https://images.unsplash.com/photo-1589924691995-400dc9ce11ff?auto=format&fit=crop&w=400&q=50',
    ownerId: 'owner-2',
    energyLevel: 'alto',
    temperament: ['inteligente', 'activo', 'protector'],
    specialNeeds: ['medicación para displasia'],
    healthStatus: 'tratamiento',
    vaccinationStatus: 'al día',
    sppiayed: true,
    description: 'Thor es un perro muy inteligente que fue abandonado por su familia. Necesita alguien con experiencia.',
    daysSinceLastWalk: 4,
    totalWalks: 15,
    preferredWalkTime: 'mañana',
    anxietyLevel: 'alto',
    size: 'grande',
    walkDurationPreferred: 40,
    goodWithKids: true,
    goodWithOtherDogs: false,
    adoptionReady: false,
    dateRescued: '2023-12-01',
    interactionHistory: [
      { date: '2026-04-24', volunteerId: 'vol-1', type: 'paseo', duration: 35, rating: 4, notes: 'Necesitó descansos por su displasia.' },
    ],
  },
  {
    id: 'dog-5',
    name: 'Mía',
    breed: 'Poodle mix',
    age: 1,
    weight: 6,
    gender: 'Hembra',
    photo: 'https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&w=400&q=50',
    ownerId: 'owner-2',
    energyLevel: 'medio',
    temperament: ['juguetona', 'curiosa', 'alegre'],
    specialNeeds: [],
    healthStatus: 'saludable',
    vaccinationStatus: 'al día',
    sppiayed: false,
    description: 'Mía es una cachorrita que fue encontrada en una caja. Está llena de energía y amor.',
    daysSinceLastWalk: 2,
    totalWalks: 10,
    preferredWalkTime: 'tarde',
    anxietyLevel: 'bajo',
    size: 'pequeño',
    walkDurationPreferred: 25,
    goodWithKids: true,
    goodWithOtherDogs: true,
    adoptionReady: true,
    dateRescued: '2025-09-05',
    interactionHistory: [
      { date: '2026-04-27', volunteerId: 'vol-3', type: 'paseo', duration: 20, rating: 5, notes: 'Adorable, todos la aman.' },
      { date: '2026-04-25', volunteerId: 'vol-2', type: 'visita', duration: 15, rating: 5, notes: 'Juguetona y tierna.' },
    ],
  },
  {
    id: 'dog-6',
    name: 'Simón',
    breed: 'Criollo (mestizo)',
    age: 8,
    weight: 20,
    gender: 'Macho',
    photo: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=400&q=50',
    ownerId: 'owner-4',
    energyLevel: 'bajo',
    temperament: ['calmado', 'noble', 'leal'],
    specialNeeds: ['artritis leve'],
    healthStatus: 'tratamiento',
    vaccinationStatus: 'al día',
    sppiayed: true,
    description: 'Simón es un abuelito que ha vivido toda su vida en las calles. Merece un retiro tranquilo y mucho amor.',
    daysSinceLastWalk: 7,
    totalWalks: 5,
    preferredWalkTime: 'mañana',
    anxietyLevel: 'alto',
    size: 'mediano',
    walkDurationPreferred: 20,
    goodWithKids: true,
    goodWithOtherDogs: true,
    adoptionReady: true,
    dateRescued: '2024-01-20',
    interactionHistory: [
      { date: '2026-04-21', volunteerId: 'vol-1', type: 'paseo', duration: 15, rating: 5, notes: 'Caminata cortita. Muy tranquilo.' },
    ],
  },
];

// Voluntarios / Paseadores
export const VOLUNTEERS = [
  {
    id: 'vol-1',
    name: 'Carlos Rodríguez',
    age: 28,
    email: 'carlos@email.com',
    experience: 'avanzado', // principiante, intermedio, avanzado
    preferredSize: ['mediano', 'grande'],
    preferredEnergy: ['alto', 'medio'],
    availability: {
      mañana: true,
      tarde: true,
      noche: false,
    },
    location: { latitude: 6.2476, longitude: -75.5658 },
    totalWalks: 45,
    totalHours: 38,
    dogsHelped: 8,
    rating: 4.9,
    reviews: 32,
    verified: true,
    verificationDate: '2025-06-15',
    institution: 'Fundación Huellas de Amor',
    bio: 'Amante de los animales. Voluntario activo desde 2025. Tengo experiencia con perros grandes y de alta energía.',
    badges: ['Paseador Estrella', 'Voluntario del Mes', '50 Paseos'],
  },
  {
    id: 'vol-2',
    name: 'María López',
    age: 24,
    email: 'maria@email.com',
    experience: 'intermedio',
    preferredSize: ['pequeño', 'mediano'],
    preferredEnergy: ['medio', 'bajo'],
    availability: {
      mañana: true,
      tarde: false,
      noche: false,
    },
    location: { latitude: 6.2510, longitude: -75.5740 },
    totalWalks: 22,
    totalHours: 18,
    dogsHelped: 5,
    rating: 4.7,
    reviews: 15,
    verified: true,
    verificationDate: '2025-09-20',
    institution: 'Patitas Sin Hogar',
    bio: 'Estudiante de veterinaria. Me encanta pasar tiempo con los perros del refugio y darles el cariño que merecen.',
    badges: ['Primera Caminata', 'Amiga de los Peludos'],
  },
  {
    id: 'vol-3',
    name: 'Andrés García',
    age: 32,
    email: 'andres@email.com',
    experience: 'principiante',
    preferredSize: ['pequeño'],
    preferredEnergy: ['bajo', 'medio'],
    availability: {
      mañana: false,
      tarde: true,
      noche: true,
    },
    location: { latitude: 6.2390, longitude: -75.5850 },
    totalWalks: 8,
    totalHours: 6,
    dogsHelped: 3,
    rating: 4.5,
    reviews: 6,
    verified: false,
    verificationDate: null,
    institution: null,
    bio: 'Nuevo en el voluntariado pero con muchas ganas de ayudar. Prefiero perros tranquilos y pequeños.',
    badges: ['Primera Caminata'],
  },
];

// Usuario actual (el que usa la app)
export const CURRENT_USER = {
  id: 'user-current',
  name: 'Alex',
  role: 'voluntario', // voluntario, refugio
  experience: 'intermedio',
  preferredSize: ['mediano', 'grande'],
  preferredEnergy: ['alto', 'medio'],
  availability: {
    mañana: true,
    tarde: true,
    noche: false,
  },
  location: { latitude: 6.2442, longitude: -75.5812 },
  totalWalks: 15,
  totalHours: 12,
  dogsHelped: 4,
  favoriteDogsIds: ['dog-1', 'dog-3'],
};

// Historial de paseos completos
export const WALK_HISTORY = [
  {
    id: 'walk-1',
    dogId: 'dog-1',
    volunteerId: 'user-current',
    date: '2026-04-28',
    startTime: '09:00',
    endTime: '09:45',
    duration: 45,
    distance: 2.3,
    route: [
      { latitude: 6.2442, longitude: -75.5812 },
      { latitude: 6.2450, longitude: -75.5800 },
      { latitude: 6.2460, longitude: -75.5790 },
      { latitude: 6.2455, longitude: -75.5785 },
    ],
    rating: 5,
    notes: 'Luna estaba muy contenta hoy. Jugamos en el parque.',
    dogMood: 'feliz',
  },
  {
    id: 'walk-2',
    dogId: 'dog-3',
    volunteerId: 'user-current',
    date: '2026-04-26',
    startTime: '15:00',
    endTime: '15:30',
    duration: 30,
    distance: 1.5,
    route: [
      { latitude: 6.2518, longitude: -75.5636 },
      { latitude: 6.2525, longitude: -75.5625 },
    ],
    rating: 5,
    notes: 'Canela caminó muy bien con correa.',
    dogMood: 'tranquila',
  },
];

// Notificaciones
export const NOTIFICATIONS = [
  {
    id: 'notif-1',
    type: 'urgencia',
    title: 'Simón necesita ayuda',
    message: 'Simón lleva 7 días sin pasear. Su nivel de ansiedad ha aumentado. ¿Puedes dedicarle 20 minutos?',
    dogId: 'dog-6',
    time: 'Hace 2 horas',
    read: false,
    priority: 'alta',
  },
  {
    id: 'notif-2',
    type: 'recomendacion',
    title: 'Nueva recomendación de IA',
    message: 'Basado en tu perfil, Luna sería una excelente compañera de paseo para ti hoy.',
    dogId: 'dog-1',
    time: 'Hace 3 horas',
    read: false,
    priority: 'media',
  },
  {
    id: 'notif-3',
    type: 'paseo_completado',
    title: 'Paseo completado',
    message: 'Tu paseo con Canela fue registrado. ¡Gracias por ayudar!',
    dogId: 'dog-3',
    time: 'Ayer',
    read: true,
    priority: 'baja',
  },
  {
    id: 'notif-4',
    type: 'logro',
    title: '¡Nuevo logro desbloqueado!',
    message: 'Has completado 15 paseos. Ahora eres un "Paseador Comprometido".',
    dogId: null,
    time: 'Hace 2 días',
    read: true,
    priority: 'baja',
  },
];

// Opciones para el formulario de perfil del usuario
export const USER_PREFERENCES = {
  experienceLevels: [
    { value: 'principiante', label: 'Principiante', description: 'Nunca he paseado perros de refugio' },
    { value: 'intermedio', label: 'Intermedio', description: 'He paseado algunos perros antes' },
    { value: 'avanzado', label: 'Avanzado', description: 'Tengo experiencia con perros difíciles' },
  ],
  dogSizes: [
    { value: 'pequeño', label: 'Pequeño', description: 'Menos de 10 kg' },
    { value: 'mediano', label: 'Mediano', description: '10 - 25 kg' },
    { value: 'grande', label: 'Grande', description: 'Más de 25 kg' },
  ],
  energyLevels: [
    { value: 'bajo', label: 'Bajo', description: 'Paseos cortos y tranquilos' },
    { value: 'medio', label: 'Medio', description: 'Paseos moderados' },
    { value: 'alto', label: 'Alto', description: 'Paseos largos y activos' },
  ],
  timeSlots: [
    { value: 'mañana', label: 'Mañana', time: '6:00 - 12:00' },
    { value: 'tarde', label: 'Tarde', time: '12:00 - 18:00' },
    { value: 'noche', label: 'Noche', time: '18:00 - 21:00' },
  ],
};

// Global state for requests to sync between screens
export const GLOBAL_REQUESTS = {
  pending: [],
  active: [],
  completed: []
};

export const addPendingRequest = (request) => {
  // Avoid duplicates
  if (!GLOBAL_REQUESTS.pending.find(r => r.id === request.id)) {
    GLOBAL_REQUESTS.pending.unshift(request);
  }
};
